@startuml 要件モデル
title 要望

actor ドッター
note right :作業エリアに切り出して作業を行いたい

actor ドッター
note right :タイル区画を簡単に選択編集したい

actor ドッター
note right :一般的なお絵かき機能の操作をしたい

actor ドッター
note right :フルカラー32bitでドット絵を描きたい

actor ドッター
note right :アルファチャンネルとRGBのレイヤーを同時および個別に操作したい

' 要件
' - タイル区画を作業エリアに切り出し、一般的なお絵かき機能の操作で編集できること
' - アルファチャンネルとRGBのレイヤーを分けて同時および個別に編集できること

@enduml