@startuml
left to right direction

actor ドッター
ドッター -- (ドット絵を開く)
(ドット絵を開く) -- (画像ファイルからプライマリ画像を開く)
(ドット絵を開く) -- (プライマリ画像を新規作成する)
ドッター -- (ドット絵を描く)
(ドット絵を描く) -- (線の太さを選択する)
(ドット絵を描く) -- (パレットから色を選択する)
(ドット絵を描く) -- (ペンツールを選択する)
(ドット絵を描く) -- (プライマリ画像から作業エリアにドット絵を転送する)
(ドット絵を描く) -- (作業エリアに右クリックでドット絵を描く)
(ドット絵を描く) -- (作業エリアから左クリックで色をスポイトする)
(ドット絵を描く) -- (作業エリアを回転する)
(ドット絵を描く) -- (作業エリアを反転する)
(作業エリアを反転する) -- (左右反転する)
(作業エリアを反転する) -- (上下反転する)
(ドット絵を描く) -- (作業エリアをシフトする)
(ドット絵を描く) -- (作業エリアを範囲選択する)
(作業エリアを範囲選択する) -- (選択範囲を操作する)
(作業エリアを範囲選択する) -- (選択範囲を移動する)
ドッター -- (ドット絵を保存する)
(ドット絵を保存する) -- (作業エリアからプライマリ画像にドット絵を転送する)
(ドット絵を保存する) -- (プライマリ画像を保存する)
(プライマリ画像を保存する) -- (名前を付けて保存する)
(プライマリ画像を保存する) -- (上書き保存する)

@enduml