<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DebugType>embedded</DebugType>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Eede.Application\Eede.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pictures\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
    <PackageReference Include="System.Reactive" Version="7.0.0" />
    <PackageReference Include="Velopack" Version="1.2.0" />
  </ItemGroup>

</Project>
